# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Compass API: Compass Labs DeFi API"
  homepage "https://github.com/CompassLabs/cli"
  version "0.1.70"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.70/compass_Darwin_x86_64.tar.gz"
      sha256 "391099602fa5c983d33391678f4e67a4db7a4d4fbaac9e9974a8556569ce9a1a"

      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.70/compass_Darwin_arm64.tar.gz"
      sha256 "d6596338a32bee93d838f87d216792d388cbda68dfe59c1f15dd438f18d6e7d8"

      define_method(:install) do
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.70/compass_Linux_x86_64.tar.gz"
      sha256 "e66a6e2799ea7fddcf428d9af67af3ccdf417e4762d9f120e501faa2476a4cc9"
      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.70/compass_Linux_arm64.tar.gz"
      sha256 "fc9008ebbf4a750727b23abc79b75ea1c4a164c4f8d126fb51f1212ddfbc522b"
      define_method(:install) do
        bin.install "compass"
      end
    end
  end
end
