# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Compass API: Compass Labs DeFi API"
  homepage "https://github.com/CompassLabs/cli"
  version "0.1.56"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.56/compass_Darwin_x86_64.tar.gz"
      sha256 "fd9c454c7c6a71a5fbb74c43e4aa6c16c2a54ec781538122edc3296e66475c62"

      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.56/compass_Darwin_arm64.tar.gz"
      sha256 "44883dd4ee94702e3293684354fb372476dc07570480fae001795305e8b368b4"

      define_method(:install) do
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.56/compass_Linux_x86_64.tar.gz"
      sha256 "d5fa383ffc233d3fdccf4f94989beb183878cf8556481f0dd8d07c968db35696"
      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.56/compass_Linux_arm64.tar.gz"
      sha256 "5b93240ec4e97fc870b05de2598de34d8e6bb8662058fcf195f5b1790e2e4465"
      define_method(:install) do
        bin.install "compass"
      end
    end
  end
end
