# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Compass API: Compass Labs DeFi API"
  homepage "https://github.com/CompassLabs/cli"
  version "0.1.40"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.40/compass_Darwin_x86_64.tar.gz"
      sha256 "a46f4dc61e3fc2d98763d121a6fee2ed52ead44cdc1236768d36a1af2cf17c59"

      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.40/compass_Darwin_arm64.tar.gz"
      sha256 "0d89257401bc05b1062ba94f78df10204b58fdaaae0c5e252ddd96ae7d51c04f"

      define_method(:install) do
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.40/compass_Linux_x86_64.tar.gz"
      sha256 "9c54f7a53c3973ea1195ee18d1466d38d27386cc527d33fc9de7a37b6017f279"
      define_method(:install) do
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CompassLabs/cli/releases/download/v0.1.40/compass_Linux_arm64.tar.gz"
      sha256 "8db957bd4f4e53e6769214cf7e0bff59641ef7764fc97aa7ecf13d2b512353e6"
      define_method(:install) do
        bin.install "compass"
      end
    end
  end
end
